
version: 2

formats: all

python:
  version: 3.6
  install:
    - requirements: requirements-docs.txt
  system_packages: true

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true


